services:
  db:
    image: postgres:16.11-alpine
    environment:
      POSTGRES_USER: ${BLOG_DB_USER}
      POSTGRES_DB: ${BLOG_DB_NAME}
      PGTZ: UTC
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "$BLOG_DB_PORT:5432"
    container_name: ${BLOG_DB_CNT_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8.4.0-alpine
    restart: always
    ports:
      - "${BLOG_REDIS_PORT}:6379"
    command: sh -c 'redis-server --requirepass $(cat /run/secrets/redis_password)'
    container_name: ${BLOG_REDIS_CNT_NAME}
    secrets:
      - redis_password
    volumes:
      - redis_data:/data

secrets:
  db_password:
    file: ${BLOG_DB_PASSWORD_FILE}
  redis_password:
    file: ${BLOG_REDIS_PASSWORD_FILE}

volumes:
  db_data:
  redis_data:


